language: bash
services: docker

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

script:
  - docker build -t "doppler-relay-php-base" .
  - ~/official-images/test/run.sh "doppler-relay-php-base"

after_script:
  - docker images

